import { v4 as uuidv4 } from "uuid";

function format() {
  return [
    {
      name: "سُورَةُ ٱلْفَاتِحَةِ",

      number: 1,
      id: uuidv4(),
      color: ["blue", "black"],
      active: true,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/001.mp3",
    },
    {
      name: "سُورَةُ البَقَرَةِ",
      number: 2,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/002.mp3",
    },
    {
      name: "سُورَةُ آلِ عِمرَانَ",
      number: 3,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/003.mp3",
    },
    {
      name: "سُورَةُ النِّسَاءِ",
      number: 4,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/004.mp3",
    },
    {
      name: "سُورَةُ المَائـِدَةِ",
      number: 5,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/005.mp3",
    },
    {
      name: "سُورَةُ الأَنعَامِ",
      number: 6,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/006.mp3",
    },
    {
      name: "سُورَةُ الأَعرَافِ",
      number: 7,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/007.mp3",
    },
    {
      name: "سُورَةُ الأَنفَالِ",
      number: 8,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/008.mp3",
    },
    {
      name: "سُورَةُ التَّوبَةِ",
      number: 9,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/009.mp3",
    },
    {
      name: "سُورَةُ يُونُسَ",
      number: 10,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/010.mp3",
    },
    {
      name: "سُورَةُ هُودٍ",
      number: 11,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/011.mp3",
    },
    {
      name: "سُورَةُ يُوسُفَ",
      number: 12,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/012.mp3",
    },
    {
      name: "سُورَةُ الرَّعدِ",
      number: 13,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/013.mp3",
    },
    {
      name: "سُورَةُ إِبرَاهِيمَ",
      number: 14,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/014.mp3",
    },
    {
      name: "سُورَةُ الحِجرِ",
      number: 15,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/015.mp3",
    },
    {
      name: "سُورَةُ النَّحلِ",
      number: 16,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/016.mp3",
    },
    {
      name: "سُورَةُ الإِسرَاءِ",
      number: 17,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/017.mp3",
    },
    {
      name: "سُورَةُ الكَهفِ",
      number: 18,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/018.mp3",
    },
    {
      name: "سُورَةُ مَريَمَ",
      number: 19,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/019.mp3",
    },
    {
      name: "سُورَةُ طه",
      number: 20,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/020.mp3",
    },
    {
      name: "سُورَةُ الأَنبِيَاءِ",
      number: 21,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/021.mp3",
    },
    {
      name: "سُورَةُ الحَجِّ",
      number: 22,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/022.mp3",
    },
    {
      name: "سُورَةُ المُؤمِنُونَ",
      number: 23,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/023.mp3",
    },
    {
      name: "سُورَةُ النُّورِ",
      number: 24,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/024.mp3",
    },
    {
      name: "سُورَةُ الفُرقَانِ",
      number: 25,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/025.mp3",
    },
    {
      name: "سُورَةُ الشُّعَرَاءِ",
      number: 26,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/026.mp3",
    },
    {
      name: "سُورَةُ النَّملِ",
      number: 27,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/027.mp3",
    },
    {
      name: "سُورَةُ القَصَصِ",
      number: 28,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/028.mp3",
    },
    {
      name: "سُورَةُ العَنكَبُوتِ",
      number: 29,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/029.mp3",
    },
    {
      name: "سُورَةُ الرُّومِ",
      number: 30,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/030.mp3",
    },
    {
      name: "سُورَةُ لُقمَانَ",
      number: 31,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/031.mp3",
    },
    {
      name: "سُورَةُ السَّجدَةِ",
      number: 32,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/032.mp3",
    },
    {
      name: "سُورَةُ الأَحزَابِ",
      number: 33,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/033.mp3",
    },
    {
      name: "سُورَةُ سَبَإٍ",
      number: 34,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/034.mp3",
    },
    {
      name: "سُورَةُ فَاطِرٍ",
      number: 35,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/035.mp3",
    },
    {
      name: "سُورَةُ يسٓ",
      number: 36,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/036.mp3",
    },
    {
      name: "سُورَةُ الصَّافَّاتِ",
      number: 37,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/037.mp3",
    },
    {
      name: "سُورَةُ صٓ",
      number: 38,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/038.mp3",
    },
    {
      name: "سُورَةُ الزُّمَرِ",
      number: 39,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/039.mp3",
    },
    {
      name: "سُورَةُ غَافِرٍ",
      number: 40,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/040.mp3",
    },
    {
      name: "سُورَةُ فُصِّلَت",
      number: 41,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/041.mp3",
    },
    {
      name: "سُورَةُ الشُّورَىٰ",
      number: 42,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/042.mp3",
    },
    {
      name: "سُورَةُ الزُّخرُفِ",
      number: 43,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/043.mp3",
    },
    {
      name: "سُورَةُ الدُّخَانِ",
      number: 44,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/044.mp3",
    },
    {
      name: "سُورَةُ الجَاثِيَةِ",
      number: 45,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/045.mp3",
    },
    {
      name: "سُورَةُ الأَحقَافِ",
      number: 46,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/046.mp3",
    },
    {
      name: "سُورَةُ مُحَمَّدٍ",
      number: 47,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/047.mp3",
    },
    {
      name: "سُورَةُ الفَتحِ",
      number: 48,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/048.mp3",
    },
    {
      name: "سُورَةُ الحُجُرَاتِ",
      number: 49,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/049.mp3",
    },
    {
      name: "سُورَةُ قٓ",
      number: 50,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/050.mp3",
    },
    {
      name: "سُورَةُ الذَّارِيَاتِ",
      number: 51,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/051.mp3",
    },
    {
      name: "سُورَةُ الطُّورِ",
      number: 52,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/052.mp3",
    },
    {
      name: "سُورَةُ النَّجمِ",
      number: 53,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/053.mp3",
    },
    {
      name: "سُورَةُ القَمَرِ",
      number: 54,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/054.mp3",
    },
    {
      name: "سُورَةُ الرَّحمَٰن",
      number: 55,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/055.mp3",
    },
    {
      name: "سُورَةُ الوَاقِعَةِ",
      number: 56,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/056.mp3",
    },
    {
      name: "سُورَةُ الحَدِيدِ",
      number: 57,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/057.mp3",
    },
    {
      name: "سُورَةُ المُجَادلَةِ",
      number: 58,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/058.mp3",
    },
    {
      name: "سُورَةُ الحَشرِ",
      number: 59,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/059.mp3",
    },
    {
      name: "سُورَةُ المُمتَحنَةِ",
      number: 60,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/060.mp3",
    },
    {
      name: "سُورَةُ الصَّفِّ",
      number: 61,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/061.mp3",
    },
    {
      name: "سُورَةُ الجُمُعَةِ",
      number: 62,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/062.mp3",
    },
    {
      name: "سُورَةُ المُنَافِقُونَ",
      number: 63,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/063.mp3",
    },
    {
      name: "سُورَةُ التَّغَابُنِ",
      number: 64,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/064.mp3",
    },
    {
      name: "سُورَةُ الطَّلَاقِ",
      number: 65,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/065.mp3",
    },
    {
      name: "سُورَةُ التَّحرِيمِ",
      number: 66,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/066.mp3",
    },
    {
      name: "سُورَةُ المُلكِ",
      number: 67,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/067.mp3",
    },
    {
      name: "سُورَةُ القَلَمِ",
      number: 68,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/068.mp3",
    },
    {
      name: "سُورَةُ الحَاقَّةِ",
      number: 69,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/069.mp3",
    },
    {
      name: "سُورَةُ المَعَارِجِ",
      number: 70,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/070.mp3",
    },
    {
      name: "سُورَةُ نُوحٍ",
      number: 71,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/071.mp3",
    },
    {
      name: "سُورَةُ الجِنِّ",
      number: 72,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/072.mp3",
    },
    {
      name: "سُورَةُ المُزَّمِّلِ",
      number: 73,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/073.mp3",
    },
    {
      name: "سُورَةُ المُدَّثِّرِ",
      number: 74,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/074.mp3",
    },
    {
      name: "سُورَةُ القِيَامَةِ",
      number: 75,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/075.mp3",
    },
    {
      name: "سُورَةُ الإِنسَانِ",
      number: 76,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/076.mp3",
    },
    {
      name: "سُورَةُ المُرسَلَاتِ",
      number: 77,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/077.mp3",
    },
    {
      name: "سُورَةُ النَّبَإِ",
      number: 78,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/078.mp3",
    },
    {
      name: "سُورَةُ النَّازِعَاتِ",
      number: 79,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/079.mp3",
    },
    {
      name: "سُورَةُ عَبَسَ",
      number: 80,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/080.mp3",
    },
    {
      name: "سُورَةُ التَّكوِيرِ",
      number: 81,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/081.mp3",
    },
    {
      name: "سُورَةُ الانفِطَارِ",
      number: 82,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/082.mp3",
    },
    {
      name: "سُورَةُ المُطَفِّفِينَ",
      number: 83,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/083.mp3",
    },
    {
      name: "سُورَةُ الانشِقَاقِ",
      number: 84,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/084.mp3",
    },
    {
      name: "سُورَةُ البُرُوجِ",
      number: 85,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/085.mp3",
    },
    {
      name: "سُورَةُ الطَّارِقِ",
      number: 86,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/086.mp3",
    },
    {
      name: "سُورَةُ الأَعلَىٰ",
      number: 87,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/087.mp3",
    },
    {
      name: "سُورَةُ الغَاشِيَةِ",
      number: 88,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/088.mp3",
    },
    {
      name: "سُورَةُ الفَجرِ",
      number: 89,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/089.mp3",
    },
    {
      name: "سُورَةُ البَلَدِ",
      number: 90,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/090.mp3",
    },
    {
      name: "سُورَةُ الشَّمسِ",
      number: 91,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/091.mp3",
    },
    {
      name: "سُورَةُ اللَّيلِ",
      number: 92,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/092.mp3",
    },
    {
      name: "سُورَةُ الضُّحَىٰ",
      number: 93,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/093.mp3",
    },
    {
      name: "سُورَةُ الشَّرحِ",
      number: 94,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/094.mp3",
    },
    {
      name: "سُورَةُ التِّينِ",
      number: 95,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/095.mp3",
    },
    {
      name: "سُورَةُ العَلَقِ",
      number: 96,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/096.mp3",
    },
    {
      name: "سُورَةُ القَدرِ",
      number: 97,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/097.mp3",
    },
    {
      name: "سُورَةُ البَيِّنَةِ",
      number: 98,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/098.mp3",
    },
    {
      name: "سُورَةُ الزَّلزَلَةِ",
      number: 99,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/099.mp3",
    },
    {
      name: "سُورَةُ العَادِيَاتِ",
      number: 100,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/100.mp3",
    },
    {
      name: "سُورَةُ القَارِعَةِ",
      number: 101,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/101.mp3",
    },
    {
      name: "سُورَةُ التَّكَاثُرِ",
      number: 102,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/102.mp3",
    },
    {
      name: "سُورَةُ العَصرِ",
      number: 103,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/103.mp3",
    },
    {
      name: "سُورَةُ الهُمَزَةِ",
      number: 104,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/104.mp3",
    },
    {
      name: "سُورَةُ الفِيلِ",
      number: 105,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/105.mp3",
    },
    {
      name: "سُورَةُ قُرَيشٍ",
      number: 106,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/106.mp3",
    },
    {
      name: "سُورَةُ المَاعُونِ",
      number: 107,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/107.mp3",
    },
    {
      name: "سُورَةُ الكَوثَرِ",
      number: 108,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/108.mp3",
    },
    {
      name: "سُورَةُ الكَافِرُونَ",
      number: 109,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/109.mp3",
    },
    {
      name: "سُورَةُ النَّصرِ",
      number: 110,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/110.mp3",
    },
    {
      name: "سُورَةُ المَسَدِ",
      number: 111,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/111.mp3",
    },
    {
      name: "سُورَةُ الإِخلَاصِ",
      number: 112,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/112.mp3",
    },
    {
      name: "سُورَةُ الفَلَقِ",
      number: 113,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/113.mp3",
    },
    {
      name: "سُورَةُ النَّاسِ",
      number: 114,
      id: uuidv4(),
      color: ["blue", "black"],
      active: false,
      url: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/114.mp3",
    },
  ];
}

export default format;

// const surahNm = [
//   "1",
//   "2",
//   "3",
//   "4",
//   "5",
//   "6",
//   "7",
//   "8",
//   "9",
//   "10",
//   "11",
//   "12",
//   "13",
//   "14",
//   "15",
//   "16",
//   "17",
//   "18",
//   "19",
//   "20",
//   "21",
//   "22",
//   "23",
//   "24",
//   "25",
//   "26",
//   "27",
//   "28",
//   "29",
//   "30",
//   "31",
//   "32",
//   "33",
//   "34",
//   "35",
//   "36",
//   "37",
//   "38",
//   "39",
//   "40",
//   "41",
//   "42",
//   "43",
//   "44",
//   "45",
//   "46",
//   "47",
//   "48",
//   "49",
//   "50",
//   "51",
//   "52",
//   "53",
//   "54",
//   "55",
//   "56",
//   "57",
//   "58",
//   "59",
//   "60",
//   "61",
//   "62",
//   "63",
//   "64",
//   "65",
//   "66",
//   "67",
//   "68",
//   "69",
//   "70",
//   "71",
//   "72",
//   "73",
//   "74",
//   "75",
//   "76",
//   "77",
//   "78",
//   "79",
//   "80",
//   "81",
//   "82",
//   "83",
//   "84",
//   "85",
//   "86",
//   "87",
//   "88",
//   "89",
//   "90",
//   "91",
//   "92",
//   "93",
//   "94",
//   "95",
//   "96",
//   "97",
//   "98",
//   "99",
//   "100",
//   "101",
//   "102",
//   "103",
//   "104",
//   "105",
//   "106",
//   "107",
//   "108",
//   "109",
//   "110",
//   "111",
//   "112",
//   "113",
//   "114",
// ];
